# AutoMind Infrastructure Outputs

# VPC Outputs
output "vpc_id" {
  description = "ID of the VPC"
  value       = module.vpc.vpc_id
}

output "vpc_cidr_block" {
  description = "CIDR block of the VPC"
  value       = module.vpc.vpc_cidr_block
}

output "private_subnets" {
  description = "List of IDs of private subnets"
  value       = module.vpc.private_subnets
}

output "public_subnets" {
  description = "List of IDs of public subnets"
  value       = module.vpc.public_subnets
}

output "intra_subnets" {
  description = "List of IDs of intra subnets"
  value       = module.vpc.intra_subnets
}

# EKS Cluster Outputs
output "cluster_id" {
  description = "EKS cluster ID"
  value       = module.eks.cluster_id
}

output "cluster_arn" {
  description = "EKS cluster ARN"
  value       = module.eks.cluster_arn
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane"
  value       = module.eks.cluster_security_group_id
}

output "cluster_iam_role_name" {
  description = "IAM role name associated with EKS cluster"
  value       = module.eks.cluster_iam_role_name
}

output "cluster_certificate_authority_data" {
  description = "Base64 encoded certificate data required to communicate with the cluster"
  value       = module.eks.cluster_certificate_authority_data
}

output "cluster_primary_security_group_id" {
  description = "Cluster security group that was created by Amazon EKS for the cluster"
  value       = module.eks.cluster_primary_security_group_id
}

output "oidc_provider_arn" {
  description = "The ARN of the OIDC Provider if enabled"
  value       = module.eks.oidc_provider_arn
}

# Node Group Outputs
output "eks_managed_node_groups" {
  description = "Map of attribute maps for all EKS managed node groups created"
  value       = module.eks.eks_managed_node_groups
}

output "eks_managed_node_groups_autoscaling_group_names" {
  description = "List of the autoscaling group names created by EKS managed node groups"
  value       = module.eks.eks_managed_node_groups_autoscaling_group_names
}

# Database Outputs
output "db_instance_endpoint" {
  description = "RDS instance endpoint"
  value       = var.use_external_db ? aws_db_instance.automind[0].endpoint : null
}

output "db_instance_id" {
  description = "RDS instance ID"
  value       = var.use_external_db ? aws_db_instance.automind[0].id : null
}

output "db_instance_address" {
  description = "RDS instance hostname"
  value       = var.use_external_db ? aws_db_instance.automind[0].address : null
}

output "db_instance_port" {
  description = "RDS instance port"
  value       = var.use_external_db ? aws_db_instance.automind[0].port : null
}

output "db_subnet_group_id" {
  description = "DB subnet group name"
  value       = aws_db_subnet_group.automind.id
}

output "db_security_group_id" {
  description = "Database security group ID"
  value       = aws_security_group.rds.id
}

# Cache Outputs
output "elasticache_replication_group_id" {
  description = "ElastiCache replication group identifier"
  value       = var.use_external_cache ? aws_elasticache_replication_group.automind[0].id : null
}

output "elasticache_primary_endpoint_address" {
  description = "Address of the endpoint for the primary node in the replication group"
  value       = var.use_external_cache ? aws_elasticache_replication_group.automind[0].primary_endpoint_address : null
}

output "elasticache_reader_endpoint_address" {
  description = "Address of the endpoint for the reader node in the replication group"
  value       = var.use_external_cache ? aws_elasticache_replication_group.automind[0].reader_endpoint_address : null
}

output "cache_subnet_group_name" {
  description = "ElastiCache subnet group name"
  value       = aws_elasticache_subnet_group.automind.name
}

output "cache_security_group_id" {
  description = "Cache security group ID"
  value       = aws_security_group.elasticache.id
}

# IAM Outputs
output "eks_admin_role_arn" {
  description = "ARN of the EKS admin IAM role"
  value       = module.eks_admins_iam_role.iam_role_arn
}

# Kubectl Configuration
output "kubectl_config" {
  description = "kubectl config as generated by the module"
  value = templatefile("${path.module}/kubectl_config.tpl", {
    cluster_name     = module.eks.cluster_id
    endpoint         = module.eks.cluster_endpoint
    ca_data          = module.eks.cluster_certificate_authority_data
    aws_region       = var.aws_region
  })
  sensitive = true
}

# Connection Information
output "database_connection_string" {
  description = "Database connection string for applications"
  value = var.use_external_db ? format(
    "postgresql://%s:%s@%s:%s/%s",
    var.db_username,
    var.db_password,
    aws_db_instance.automind[0].address,
    aws_db_instance.automind[0].port,
    var.db_name
  ) : null
  sensitive = true
}

output "redis_connection_string" {
  description = "Redis connection string for applications"
  value = var.use_external_cache ? format(
    "redis://%s:%s",
    aws_elasticache_replication_group.automind[0].primary_endpoint_address,
    6379
  ) : null
  sensitive = true
}

# Environment Information
output "environment" {
  description = "Environment name"
  value       = var.environment
}

output "aws_region" {
  description = "AWS region"
  value       = var.aws_region
}

output "project_name" {
  description = "Project name"
  value       = var.project_name
}

# Deployment Commands
output "deployment_commands" {
  description = "Commands to deploy the application"
  value = {
    configure_kubectl = "aws eks update-kubeconfig --region ${var.aws_region} --name ${module.eks.cluster_id}"
    apply_kubernetes  = "kubectl apply -k k8s/"
    check_pods       = "kubectl get pods -n automind"
    check_services   = "kubectl get services -n automind"
    port_forward_api = "kubectl port-forward -n automind service/automind-api-service 8000:8000"
    port_forward_grafana = "kubectl port-forward -n automind service/grafana-service 3000:3000"
  }
}

# Monitoring URLs (when using port-forward)
output "monitoring_urls" {
  description = "URLs for monitoring services (when using port-forward)"
  value = {
    api_health    = "http://localhost:8000/api/v1/health"
    api_docs      = "http://localhost:8000/docs"
    grafana       = "http://localhost:3000"
    prometheus    = "http://localhost:9090"
  }
}